version: "3.9"

services:
  java_app:
    container_name: java_app_backend
    image: josecolins1oo/crudsalon1:backend
    build: ./back-CrudSalon
    ports:
      - 8585:8585

    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres_db
    networks:
      - proyecto1
    volumes:
      - /var/lib/docker/volumes/respaldoback/_data"

  angular_app:
    container_name: angular_app_frontend
    image: josecolins1oo/crudsalon1:frontend
    build: ./front-CrudSalon
    ports:
      - 4201:4200
    depends_on:
      - java_app
    volumes:
      - /var/lib/docker/volumes/respaldofront/_data

  postgres_db:
    container_name: postgres_db
    image: josecolins1oo/crudsalon1:bd
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - proyecto1
    volumes:
      - /var/lib/docker/volumes/respaldobd/_data


networks:
  proyecto1:
